remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Gus Robinson | Research Associate, NWEA Learning Sciences
description: Gus Robinson is a research associate at NWEA Learning Sciences. His research focuses on student growth, curricualar opportunities, and equity in education.
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics:
